version: '3.7'
services:
  frontend:
    image: docker.ub.gu.se/fjarrkontrollen-frontend:${FRONTEND_GIT_REVISION}
    ports:
      - ${FRONTEND_HOST_PORT}:8080
  backend:
    image: docker.ub.gu.se/fjarrkontrollen-backend:${BACKEND_GIT_REVISION}
  db:
    image: docker.ub.gu.se/fjarrkontrollen-postgres:${BACKEND_GIT_REVISION}
  forms_frontend:
    image: docker.ub.gu.se/fjarrkontrollen-forms-frontend:${FORMS_GIT_REVISION}
    ports:
      - ${FORMS_FRONTEND_HOST_PORT}:8080
  forms_backend:
    image: docker.ub.gu.se/fjarrkontrollen-forms-backend:${FORMS_GIT_REVISION}
  forms_db:
    image: docker.ub.gu.se/fjarrkontrollen-forms-postgres:${BACKEND_GIT_REVISION}
