version: '3.7'
services:
  mailpit:
    image: axllent/mailpit
    environment:
      - MP_UI_AUTH=${MAILPIT_USER}:${MAILPIT_PASS}
      - MP_WEBROOT=/mail/
    ports:
      - ${MAILPIT_HOST_PORT}:8025
    networks:
      - backend
